Android: Migrate to NDK r21.
EasyRPG/buildscripts pull request #101
Opened 2021-03-11 18:41 UTC by Ghabry

Do not always pull liblcf and Player repo

Fix #54

This strange looking ``./cmdline-tools/latest/bin/sdkmanage`` path is needed. The sdkmanager tells you that it wants this path. sdk_root arg still works but this breaks CMake...

NDK is now fetched via sdk manager :+1:

2021-03-11 18:51 UTC, fdelapena approved these changes

2021-03-11 18:59 UTC, carstene1ns requested changes

2021-03-11 18:59 UTC, carstene1ns commented on android/2_build_toolchain.sh
> +	export CC="clang -target ${4}${TARGET_API}"
`4`→`TARGET_HOST`

2021-03-11 18:59 UTC, carstene1ns commented on android/4_build_liblcf.sh
>  	git -C liblcf pull
This makes no sense.
When there is no .git directory there is nothing to pull.

2021-03-11 19:07 UTC, Ghabry commented
Adressed the review comments.
Better don't merge this stuff before Monday. I won't be at home before and Jenkins needs lots of updates for this ^^'

2021-03-13 08:30 UTC, carstene1ns approved these changes

2021-03-17 16:34 UTC, Ghabry commented
this is mergeable now

2021-03-17 16:35 UTC, merged